trigger:
  branches:
    include:
      - main

pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  Runtime: 'linux-x64'

steps:
  - task: DotNetCoreCLI@2
    name: Restore
    inputs:
      command: 'restore'
      arguments: '-r $(Runtime)'
  - task: DotNetCoreCLI@2
    name: Build
    inputs:
      command: 'build'
      arguments: '-c Release -r $(Runtime)'
  - task: DotNetCoreCLI@2
    name: Publish
    inputs:
      command: 'publish'
      arguments: '-c Release -r $(Runtime) -p:PublishReadyToRun=true -o publish'
  - task: PublishBuildArtifacts@1
    name: Pack
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'