version: '3.1'

services:
  spotify-telegram-bot:
    container_name: spotify-telegram-bot
    image: infinitu1327/spotifybot
    depends_on:
      - telegram-bot-api
    ports:
      - "65502:80"
    environment:
      Telegram:Token:
      Spotify:ClientId:
      Spotify:ClientSecret:
      ApplicationInsights:InstrumentationKey:
  telegram-bot-api:
    image: aiogram/telegram-bot-api:latest
    ports:
      - "65500:8081"
    environment:
      TELEGRAM_API_ID:
      TELEGRAM_API_HASH:
      TELEGRAM_LOCAL: 'true'