version: '3.1'

services:
  spotify-telegram-bot:
    container_name: spotify-telegram-bot
    build:
      context: .
      dockerfile: ./Bot/Dockerfile
    image: spotify-telegram-bot:latest
    depends_on:
      - telegram-bot-api
    ports:
      - "65502:80"
    environment:
      Telegram:Token:
      Telegram:ApiUrl:
      Spotify:ClientId:
      Spotify:ClientSecret:
      ApplicationInsights:InstrumentationKey:
  telegram-bot-api:
    image: aiogram/telegram-bot-api:latest
    ports:
      - "65500:8081"
    volumes:
      - /telegram-bot-api-data:/var/lib/telegram-bot-api
    environment:
      TELEGRAM_API_ID:
      TELEGRAM_API_HASH:
      TELEGRAM_LOCAL: 'true'