name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker-compose -f ./docker-compose.yml build
      - name: Run docker container
        run: docker-compose -f ./docker-compose.yml -f /root/spotify-telegram-bot-copy.yml -d
